### PR TITLE
 Modified the whole style of website.

### PR DESCRIPTION
**Pull request by baishalicode123**

### CODE REVIEW

**Comment by ankitmalakar7** [comment]
Please make a `git pull` once in your terminal as it has more than one merge conflict.
Secondly, please add those markers before each profile tag, that's alright, but don't change the color combination of the present site.
Even your idea to add the progress in the footer also seems good to me.

**Comment by baishalicode123** [comment]
Thanks a lot!
I will do the required changes.

**Comment by baishalicode123** [comment]
not changing Colour combination means do i need to change the colour of the profile list ?

**Comment by ankitmalakar7** [comment]
All okay but for mobile devices it looks like
image

Can you please try to resolve it?

**Comment by baishalicode123** [comment]
Kindly check if it's correct

**Comment by ankitmalakar7** [comment]
Not yet 😶‍🌫️... Sorry but Baishali you please inspect it in any mobile device, You'll see H is not visible of Hacktoberfest, same in 2nd line also. 
I can suggest you to leave this PR, do small changes at a time & give PR. I'll merge them & it will also help u to complete your whole progress.

**Pull request closed without merging**
